service: quotes

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1
  memorySize: 128
  profile: profile_serverless
  tracing: true # enable tracing
  iamRoleStatements:
    - Effect: "Allow" # xray permissions (required)
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"
  vpc:
    securityGroupIds:
      - sg-1e536766 # default
    subnetIds:
      - subnet-1460ef3e
      - subnet-67fa9a02
      - subnet-8c3f70b1
      - subnet-9467f0cc
      - subnet-a9f48adf
      - subnet-ab3cbea7
  environment:
    MYSQLHOST: 'sls-rds.cluster-chdypprh6om2.us-east-1.rds.amazonaws.com'
    MYSQLPORT: 3306
    MYSQLUSER: 'root'
    MYSQLPASS: 'May2019.'
    MYSQLDATABASE: 'exampledb'
    ENVIRONMENT: 'DEV'

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-plugin-tracing

custom:
  wsgi:
    app: app.app
    packRequirements: false

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
